change printing error.
example:

 fly error !
    master init error. ("Address already in use")

Traceback (most recent call last):
  File "/home/tatsuya/fly/fly/app.py", line 255, in _start_server
    super()._configure(self.config_path, self.routes)
Exception: master init error. ("Address already in use")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tatsuya/fly/fly/app.py", line 102, in _run
    fly._start_server(fly._daemon)
  File "/home/tatsuya/fly/fly/app.py", line 257, in _start_server
    raise _FLY_MASTER_CONFIGURE_ERROR(e) from e
fly.app._FLY_MASTER_CONFIGURE_ERROR: master init error. ("Address already in use")